apiVersion: v1
kind: Namespace
metadata:
  name: sno1-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno1
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sno1-sub
  project: ztp-app-project
  source:
    path: sno1/siteconfig
    repoURL: https://github.com/TerryHu82/acm-ztp.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
