apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: "three-nodes"
  namespace: "three-nodes"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  apiVIP: 10.0.78.150
  ingressVIP: 10.0.78.150