apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "three-nodes"
  namespace: "three-nodes"
spec:
  baseDomain: "terryhu.cc"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "openshift-4.18" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDR0CfciRfP6zx3M1sdPRlIPKmv+YuI2XeazmjbEiafmgOgQ70JVjaxV0IzczVeJ5cZxf2m8ZLh/LridvMIoAV4rQofiopgdPnYafnBqlCY1vnlFnxYN6dDpEz8tgIULOkpILHp1C77Tjiq0S/EAMA02ShA2wrzR7LVAJl967Ct9zke0oWwahYynxNp8UTtUMJeq6xGfjZEjdTRF3LPmgmeb9ErrZ9+fFTBLh5LU4hW91+rc+3bEGi4QgknA7TkjqslBfycEuAqIGcfPIjRoSP9iMv274ijEOt7SHENpQQ+ar/sfA8N0E94gqBVvOHAh/sfKo7hC6HoWjm9DnP4ngfOCgKMlB8v4/xRpGgQ8ACFNIsIkFU+wGJ1DvmgrMqMqGD0VKakW8/tjgKLGlPMLyHHbLlOBb+xoMNkqRAtdAgkLLFhvqlET/fmmhBduOIP+bEdMgQ5Rga/PEE9ncsCVdbhOfMUKCHOcE/ELbV7nQGOuig7d61zfuB6GxuU1jvIRl8= root@bastion-dsal.terryhu.cc"
  clusters:
  - clusterName: "three-nodes"
    # extraManifestPath: three-nodes-extra-manifest
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-3node-ranGen.yaml will apply to all clusters with 'group-du-3node: ""'
      group-du-3node: ""
      # ../policygentemplates/example-multinode-site.yaml will apply to all clusters with 'sites: "example-multinode"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "three-nodes"
    crTemplates:
      AgentClusterInstall: "agentclusterinstall.yaml"
    additionalNTPSources:
      - 10.0.79.130
    nodes:
      - hostName: "dell-r640-072.three-nodes.terryhu.cc"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "idrac-virtualmedia+https://dell-r640-072-drac.bkr.mgmt.lab.eng.rdu2.dc.redhat.com/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "three-nodes-bmc-secret"
        bootMACAddress: "78:ac:44:3b:3e:74"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "78:ac:44:3b:3e:74"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.6.56.110
                      prefix-length: 24
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                  - redhat.com
                server:
                  - 10.11.5.160
                  - 10.2.70.215
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: eno1
                  next-hop-address: 10.6.56.254
                  table-id: 254
      - hostName: "dell-r640-075.three-nodes.terryhu.cc"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "idrac-virtualmedia://dell-r640-075-drac.bkr.mgmt.lab.eng.rdu2.dc.redhat.com/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "three-nodes-bmc-secret"
        bootMACAddress: "78:ac:44:3b:39:c8"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "78:ac:44:3b:39:c8"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.6.56.113
                      prefix-length: 24
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                  - redhat.com
                server:
                  - 10.11.5.160
                  - 10.2.70.215
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: eno1
                  next-hop-address: 10.6.56.254
                  table-id: 254
      - hostName: "dell-r640-008.three-nodes.terryhu.cc"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "idrac-virtualmedia://dell-r640-008-drac.bkr.mgmt.lab.eng.rdu2.dc.redhat.com/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "three-nodes-bmc-secret"
        bootMACAddress: "e4:43:4b:6d:14:d4"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "e4:43:4b:6d:14:d4"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.6.56.25
                      prefix-length: 24
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                  - redhat.com
                server:
                  - 10.11.5.160
                  - 10.2.70.215
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: eno1
                  next-hop-address: 10.6.56.254
                  table-id: 254
      - hostName: "dell-r640-006.three-nodes.terryhu.cc"
        role: "worker"
#        crAnnotations:
#          add:
#            BareMetalHost:
#              bmac.agent-install.openshift.io/remove-agent-and-node-on-delete: true
#        crSuppression:
#        - BareMetalHost
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "idrac-virtualmedia+https://dell-r640-006-drac.bkr.mgmt.lab.eng.rdu2.dc.redhat.com/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "three-nodes-bmc-secret"
        bootMACAddress: "e4:43:4b:6c:d6:2c"
        # Use UEFISecureBoot to enable secure boot, UEFI to disable.
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/disk/by-path/pci-0000:18:00.0-scsi-0:2:0:0"
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "e4:43:4b:6c:d6:2c"
            - name: eno2
              macAddress: "e4:43:4b:6c:d6:2d"
            - name: ens1f0
              macAddress: "3c:fd:fe:79:2e:30"
            - name: ens1f1
              macAddress: "3c:fd:fe:79:2e:31"
            - name: ens1f2
              macAddress: "3c:fd:fe:79:2e:32"
            - name: ens1f3
              macAddress: "3c:fd:fe:79:2e:33"
          config:
            interfaces:
              - name: bond0
                description: Bonding eno1 and eno2
                type: bond
                state: up
                link-aggregation:
                  mode: active-backup
                  options:
                    miimon: '100'
                  port:
                  - eno1
                  - eno2
                mtu: 1500
                ipv4:
                  enabled: true
                  address:
                  - ip: 10.6.56.249
                    prefix-length: 24
                  dhcp: false
                ipv6:
                  enabled: false
              # disable ens1f0 to ens1f3
              - name: ens1f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: ens1f1
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: ens1f2
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: ens1f3
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
            dns-resolver:
              config:
                search:
                - redhat.com
                server:
                - 10.11.5.160
                - 10.2.70.215
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: bond0
                next-hop-address: 10.6.56.254
                table-id: 254
