apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "upgrade-41801-41808"
  namespace: "ztp-policies"
spec:
  bindingRules:
    common: "true"
    du-profile: "latest"
  mcp: "master"
  remediationAction: inform
  sourceFiles:
    - fileName: ClusterVersion.yaml
      complianceType: mustonlyhave
      policyName: "version-41801-41808"


