apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "upgrade"
  namespace: "ztp-policies"
spec:
  bindingRules:
    common: "true"
    du-profile: "latest"
  mcp: "master"
  remediationAction: inform
  sourceFiles:
    - fileName: ClusterVersion.yaml
      complianceType: mustnothave
      policyName: "version-41801-41808"
      metadata:
        name: version
      spec:
        channel: "stable-4.18"
        desiredUpdate:
          version: "4.18.8"
      status:
        history:
          - version: "4.18.8"
            state: "Completed"

