apiVersion: v1
kind: Namespace
metadata:
  name: three-nodes-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-nodes
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: three-nodes-sub
  project: ztp-app-project
  source:
    path: three-nodes/siteconfig
    repoURL: https://github.com/TerryHu82/acm-ztp.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
