apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-remove
  namespace: ztp-policies
spec:
  clusters:
  - three-nodes
  enable: true
  managedPolicies:
  - three-nodes-update-41801-41808-version-41801-41808
  remediationStrategy:
    maxConcurrency: 2
    timeout: 240
    batchTimeoutAction:
