apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: update-three-nodes-41801-41822
  namespace: ztp-policies
spec:
  backup: false
  clusters:
  - three-nodes
  enable: true
  managedPolicies:
  - three-nodes-update-41801-41808-version-41801-41808
  remediationStrategy:
    maxConcurrency: 2
    timeout: 15
