apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: upgrade
placementBindingDefaults:
    name: upgrade-placement-binding
policyDefaults:
    namespace: ztp-group-du-sno
    placement:
        labelSelector:
           common: "true"
           du-profile: "latest"
    remediationAction: inform
    severity: low
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: upgrade-platform-upgrade
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "1"
      manifests:
        - path: ../source-crs/ClusterVersion.yaml 
          patches:
            - metadata:
                name: version
              spec:
                channel: stable-4.18
                desiredUpdate:
                    version: 4.18.8
                upstream: https://api.openshift.com/api/upgrades_info/v1/graph
              status:
                history:
                    - state: Completed
                      version: 4.18.8
